"""numero=[]
for i in range(10):
    numero.append(i*2)
print(numero)    
    
numeros=[]
for x in range(10):
    numero.append(i**2)
print(f"numeros cargados {numero}")    


caudrados=[]
for x in  range(10):
    caudrados.append(x**2)
print(caudrados)    
"""""

pares=[]
inpares=[]
for i in range(10):
    if i%2==0:
        pares.append(i)
    else:
        inpares.append(i)
        
        
print(f"numeros pares {pares}")
print(f"numeros inpares {inpares}")        
        